routes/web.php
<?php

use App\Http\Controllers\PermissionController;
use App\Http\Controllers\PostCategoriesPageActionController;
use App\Http\Controllers\PostCategoryController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\RolePageActionController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('sign-up', function () {
    return view('sign-up');
});

Route::get('verify-employee', function () {
    return view('verify-employee');
});

Route::get('/foo/{id}', [UserController::class, 'foo'])->name('foo.index');

// Route::put('/foo/{modelos}', [UserController::class, 'updateModelos'])->name('modelos.update');
Route::put('/foo1/{requisitos}', [UserController::class, 'updateRequisitos'])->name('requisitos.update');
Route::put('/foo2/{fundamento}', [UserController::class, 'updateFundamento'])->name('fundamento.update');
Route::put('/foo3/{excepciones}', [UserController::class, 'updateExcepciones'])->name('excepciones.update');
Route::put('/foo4/{periodicidad}', [UserController::class, 'updatePeriodicidad'])->name('periodicidad.update');
Route::put('/foo5/{observaciones}', [UserController::class, 'updateObservaciones'])->name('observaciones.update');
Route::put('/foo6/{consideraciones}', [UserController::class, 'updateConsideraciones'])->name('consideraciones.update');

Route::group(['middleware' => 'auth'], function () {
    Route::get('/home', function () {
        return view('home');
    })->name('home');

    Route::resource('users', UserController::class)->only([
        'index', 'store', 'show', 'update', 'destroy'
    ]);

    // Index page for roles and permissions crud
    Route::get('/roles-permissions', RolePageActionController::class)->name('roles.index');

    // CRUD operations for roles and permissions
    Route::resource('roles', RoleController::class)->only([
        'store', 'show', 'update', 'destroy'
    ]);

    Route::resource('permissions', PermissionController::class)->only([
        'store', 'show', 'update', 'destroy'
    ]);

    // Index page for post categories
    // Route::get('/post-categories', PostCategoriesPageActionController::class)->name('post-categories.index');

    Route::get('/post-categories/show-options/{post_category}', [PostCategoryController::class, 'getCategories'])
    ->name('post-categories.show-options')
    ->where('PostCategory', '[0-9]+');

    Route::resource('post-categories', PostCategoryController::class)->only([
        'index', 'store', 'show',
    ]);

    Route::put('/post-categories/{id?}', [PostCategoryController::class, 'update'])->name('post-categories.update');

    // Route::get('/roles/get-users/{id}', [RoleController::class, 'getUsersByRole']);

    // Route::post('/roles/assign-role-to-users/', [RoleController::class, 'assignRoleToUsers']);

    // Route::get('/roles/get-permissions/{id}', [RoleController::class, 'getPermissionsByRole']);

    // Route::post('/roles/assign-permissions-to-role/', [RoleController::class, 'assignPermissionsToRole']);
});

app/Models/User.php
<?php

namespace App\Models;

// use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;
use Spatie\Permission\Traits\HasRoles;

class User extends Authenticatable
{
    use HasRoles, HasApiTokens, HasFactory, Notifiable;

    // Model column alias
    protected $maps = [
        'ape_pat' => 'paterno',
        'ape_mat' => 'materno',

        // 'username' => 'usuario',
        // 'is_active' => 'estatus',
        // 'is_password_updated' => 'ingreso',
    ];

    protected $appends = [ 'paterno', 'materno' ];

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'nombre',
        'ape_pat',
        'ape_mat',
        'username',
        'is_active',
        'is_password_updated',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',

        'ape_pat',
        'ape_mat',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function getNombreCompletoAttribute(): string
    {
        return "{$this->nombre} {$this->ape_pat} {$this->ape_mat}";
    }

    public function getPaternoAttribute()
    {
        return $this->attributes['ape_pat'];
    }

    public function getMaternoAttribute()
    {
        return $this->attributes['ape_mat'];
    }

    // Método de acceso para obtener las iniciales de nombre y apellido
    public function getInicialesAttribute()
    {
        $iniciales = substr($this->nombre, 0, 1);

        if ($this->ape_pat) {
            $iniciales .= substr($this->ape_pat, 0, 1);
        } elseif ($this->ape_mat) {
            $iniciales .= substr($this->ape_mat, 0, 1);
        }

        return strtoupper($iniciales);
    }
}

app/View/Components/FooterLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class FooterLayout extends Component
{
    /**
     * Create a new component instance.
     *
     * @return void
     */
    public function __construct()
    {
        //
    }

    /**
     * Get the view / contents that represent the component.
     *
     * @return \Illuminate\Contracts\View\View|\Closure|string
     */
    public function render()
    {
        return view('layouts.partials.footer');
    }
}

app/View/Components/MenuLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class MenuLayout extends Component
{
    /**
     * Create a new component instance.
     *
     * @return void
     */
    public function __construct()
    {
        //
    }

    /**
     * Get the view / contents that represent the component.
     *
     * @return \Illuminate\Contracts\View\View|\Closure|string
     */
    public function render()
    {
        return view('layouts.partials.menu');
    }
}

app/View/Components/VerticalMenuLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class VerticalMenuLayout extends Component
{
    /**
     * Create a new component instance.
     *
     * @return void
     */
    public function __construct()
    {
        //
    }

    /**
     * Get the view / contents that represent the component.
     *
     * @return \Illuminate\Contracts\View\View|\Closure|string
     */
    public function render()
    {
        return view('layouts.partials.vertical-menu');
    }
}

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{{ $title ?? config('app.name') }}</title>

    <link rel="stylesheet" href="{{ asset('css/tabler-new.min.css') }}">

    <link rel="stylesheet" href="{{ asset('css/tabler-vendors.css') }}">
    @stack('styles')

    <meta name="csrf-token" content="{{ csrf_token() }}">
</head>
<body>
    <div class="page">
        <!-- Navbar -->
        <header class="navbar navbar-expand-md d-print-none">
            <div class="container-xl">
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbar-menu"
                    aria-controls="navbar-menu" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <!-- Header logo -->
                <div class="navbar-brand d-none-navbar-horizontal pe-0 pe-md-3">
                    <!-- <img src="{{asset('img/')}}" width="110" height="32" alt="" class="navbar-brand-image"> -->
                </div>
                <div class="navbar-nav flex-row order-md-last">

                    @auth

                    <div class="nav-item dropdown">
                        <a href="#" class="nav-link d-flex lh-1 text-reset p-0" data-bs-toggle="dropdown"
                            aria-label="Abrir menú de usuario">
                            <span class="avatar avatar-sm">{{ auth()->user()->iniciales }}</span>
                            <div class="d-none d-xl-block ps-2">
                                <div>{{ auth()->user()->nombre_completo }}</div>
                                <div class="mt-1 small text-muted">{{ auth()->user()->email }}</div>
                            </div>
                        </a>
                        <div class="dropdown-menu dropdown-menu-end dropdown-menu-arrow">
                            <a href="#" class="dropdown-item" onclick="document.getElementById('logout-form').submit()">
                                <svg xmlns="http://www.w3.org/2000/svg" class="icon dropdown-item-icon" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">
                                    <path stroke="none" d="M0 0h24v24H0z" fill="none"></path>
                                    <path d="M14 8v-2a2 2 0 0 0 -2 -2h-7a2 2 0 0 0 -2 2v12a2 2 0 0 0 2 2h7a2 2 0 0 0 2 -2v-2"></path>
                                    <path d="M7 12h14l-3 -3m0 6l3 -3"></path>
                                </svg>
                                Cerrar sesión
                            </a>
                            <form action="{{ route('logout') }}" method="POST" id="logout-form">
                                @csrf
                            </form>
                        </div>
                    </div>
                    @endauth

                </div>
            </div>
        </header>
        <div class="navbar-expand-md">
            <div class="collapse navbar-collapse" id="navbar-menu">
                <div class="navbar navbar-light">
                    <div class="container-xl">

                        <x-menu-layout/>

                    </div>
                </div>
            </div>
        </div>
        <div class="page-wrapper">

            {{ $slot }}

            <x-footer-layout/>

        </div>
    </div>

    @stack('modals')

    <script src="{{asset('js/tabler.min.js')}}" defer></script>

    @stack('scripts')

</body>
</html>

resources/views/layouts/vertical.blade.php
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{{ $title ?? config('app.name') }}</title>
    <link rel="stylesheet" href="{{ asset('css/tabler.css') }}">
    @stack('styles')

    <meta name="csrf-token" content="{{ csrf_token() }}">
</head>
<body>
    <!-- <script src="{{-- asset('js/demo-theme.min.js') --}}"></script> -->
    <script src="{{ asset('js/tabler.min.js') }}"></script>
    <div class="page">
        <!-- Sidebar -->
        <aside class="navbar navbar-vertical navbar-expand-lg" data-bs-theme="dark">
            <div class="container-fluid">
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#sidebar-menu"
                    aria-controls="sidebar-menu" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <h1 class="navbar-brand">
                    <a href="#">
                        <img src="" width="110" height="32" alt="LOGO" class="navbar-brand-image">
                    </a>
                </h1>
                <div class="navbar-nav flex-row d-lg-none">
                    <div class="nav-item dropdown">
                        <a href="#" class="nav-link d-flex lh-1 text-reset p-0" data-bs-toggle="dropdown"
                            aria-label="Open user menu">
                            <span class="avatar avatar-sm" style="background-image: url()">RV</span>
                            <div class="d-none d-xl-block ps-2">
                                <div>Nombre</div>
                                <div class="mt-1 small text-secondary">Rol</div>
                            </div>
                        </a>
                        <div class="dropdown-menu dropdown-menu-end dropdown-menu-arrow">
                            <a href="#" class="dropdown-item">Rol 1</a>
                            <a href="#" class="dropdown-item">Rol 2</a>
                            <div class="dropdown-divider"></div>
                            <a href="./sign-in.html" class="dropdown-item">Cerrar sesión</a>
                        </div>
                    </div>
                </div>

                <!-- Menú de la Sidebar -->
                <div class="collapse navbar-collapse" id="sidebar-menu">

                    <x-vertical-menu-layout />

                </div>
            </div>
        </aside>
        <header
            class="navbar navbar-expand-md d-flex flex-wrap align-items-center justify-content-center justify-content-md-between p-3 border-bottom">
            <div class="nav col-12 justify-content-center">
                <div class="navbar-brand">
                    <!-- <img src="{{asset('img/membrete.svg')}}" width="110" height="32" alt="SET" class="navbar-brand-image"> -->
                </div>
            </div>
        </header>
        <div class="page-wrapper">
            {{ $slot }}
            <!-- Aquí va el footer -->
        </div>
    </div>

    @stack('scripts')
</body>

</html>